// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://etbkgvpkyylkufqtrwcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0YmtndnBreXlsa3VmcXRyd2NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NTQ5NjgsImV4cCI6MjA2NzMzMDk2OH0.-OHKKc5Uq21kf9wOdiXXNez-_BgI3PzUBp2QxSC8A9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);